### ISSUE TITLE
Webcompat triaged bugs marked as duplicates don't get their webcompat flag transfered

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/relman-auto-nag#1874] opened 2023-02-07 14:17 UTC
The webcompat team has flags to triage bugs in Bugzilla (often because it is a bug in Gecko), their flags are documented here:
https://wiki.mozilla.org/Compatibility/WebCompat_Priority_Flags

Relman evaluates bugs with a webcompat impact for uplifting. I noticed today that a bug which was webcompat triaged but then marked as a duplicate of another bug doesn't have the flags set on the bugs it was duped to/ Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1813470

The flag should be transferred and if the webcompat flags were set on both bugs but with diverging priorities (P2 vs P3 for example), then the bug should be updated with the highest one.

Thanks!

Pascal

**Comment by suhaibmujahid** [comment] 2023-02-08 18:11
> if the webcompat flags were set on both bugs but with diverging priorities (P2 vs P3 for example), then the bug should be updated with the highest one.

I guess it could be anoying to overwrite the value if the original bug was webcompat triaged. Transferring the value only if the original bug does not have a webcompat priority could be less noisy. @pascalchevrel wdyt?

**Comment by marco-c** [comment] 2023-02-08 18:34
This would be similar to the severity case, when somebody dupes a S2 to a S3, we know maybe in the S3 they overlooked something. Maybe instead of overwriting we could ask?
I guess in most cases the overwriting would be OK though in the webcompat case, @ksy36 what do you think?

**Comment by suhaibmujahid** [comment] 2023-02-08 18:44
> This would be similar to the severity case, when somebody dupes a S2 to a S3, we know maybe in the S3 they overlooked something. Maybe instead of overwriting we could ask? 

Yes, this is what we do in case of severity. We have a detected tool to do that: [severity_higher_dups](https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/severity_higher_dups.py)

**Comment by ksy36** [comment] 2023-02-08 20:00
> This would be similar to the severity case, when somebody dupes a S2 to a S3, we know maybe in the S3 they overlooked something. Maybe instead of overwriting we could ask? I guess in most cases the overwriting would be OK though in the webcompat case, @ksy36 what do you think?

Thinking that asking might be better, since we usually also move all webcompat issues from the duplicate's `see_also` field to the original bug, so they don't get lost. So maybe having a reminder to adjust the webcompat priority/move issues from `see also` field in this case would be nice.

**Comment by suhaibmujahid** [comment] 2023-02-09 00:58
@ksy36 when we copy the `Webcompat Priority` field, should we consider copying all values (including `-`, `?`, and `revisit`) or just the priority levels (`P1`, `P2`, and `P3`)?

**Comment by ksy36** [comment] 2023-02-15 17:36
> @ksy36 when we copy the `Webcompat Priority` field, should we consider copying all values (including `-`, `?`, and `revisit`) or just the priority levels (`P1`, `P2`, and `P3`)?

Yes, copying over `?`, `revisit` and the the priority levels  (`P1`, `P2`, and `P3`) makes sense. 

We use `-` to unset the webcompat priority (for example, when a bug is not related to web compatibility, but rather a performance issue), so likely it is not needed on the original bug. But if just copying it makes it easier (i.e. to avoid creating a special case for just this value), then it's fine.

**Comment by suhaibmujahid** [comment] 2023-02-16 00:25
The implementation in #1883 will do the following:
- When a bug gets closed as a duplicate, and it has `Webcompat Priority` set to `P1`, `P2`, `P3`, `?` or `revisit`, the bot will copy the value to the original bug.
- If the value is `revisit`, it will be copied as `?`.
- If the`Webcompat Priority` on the original bug has any value other than `--`, the bug will be ignored (we could have a separate tool to notify about inconsistency).
- If more than one duplicate of the same original bug has a value in the `Webcompat Priority` field (considering that the value on the original bug is `--`), the greater value will be copied. For example, if we have three dups with `P1`, `P2` and `?`, the bot will copy `P1`.

**Comment by marco-c** [comment] 2023-02-16 23:24
> If theWebcompat Priority on the original bug has any value other than --, the bug will be ignored (we could have a separate tool to notify about inconsistency).

Shouldn't we be needinfoing/commenting in this case to surface the inconsistency and avoid missing the importance of the bug?

**Comment by suhaibmujahid** [comment] 2023-02-17 01:04
> Shouldn't we be needinfoing/commenting in this case to surface the inconsistency and avoid missing the importance of the bug?

Yes, I was thinking of doing that in a separate tool similar to the severity case. But now thinking about it again, it may be worth refactoring this tool to be more modular and needinfoing/commenting about the inconsistency here (for Severity, Webcompat Priority, and any other future case).

**Closed as completed** 2023-02-17 13:37 UTC
Labels: enhancement, area-Metadata improvements
