### ISSUE TITLE
[close intermittents] bugs with all dependencies resolved should be close for inactivity

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/relman-auto-nag#2009] opened 2023-04-24 23:53 UTC
Dale mentioned open bugs without new intermittent failures and the pattern seems to be these bugs have dependencies but those bugs are all resolved. Without recent failures, the open intermittent bugs should be resolved.

**Comment by suhaibmujahid** [comment] 2023-04-25 00:12
Duplicate of #1994

**Closed by suhaibmujahid** 2023-04-25 00:12 UTC
