### ISSUE TITLE
Make the "copy duplicate info" script add a comment when it acts

### ISSUE THREAD

**Issue by amccreight** [mozilla/relman-auto-nag#1159] opened 2021-09-17 16:37 UTC
It looks like bugbug is automatically inserting signatures based on crash reports in comments, which is nice. But it generates signatures like [@ mozilla::dom::workerinternals::RuntimeService::CrashIfHanging()] which are invalid because crash-stats will never generate a signature with (). Ideally of course bugbug would use the full signature processing logic of socorro, but at a minimum it would be nice if it used whatever logic crash-stats uses to remove the () so we won't get completely invalid signatures

https://bugzilla.mozilla.org/show_bug.cgi?id=1435343#a114297115_575867

**Comment by marco-c** [comment] 2021-09-17 16:41
Moved to the autonag repository as the problem is not in bugbug.

**Comment by marco-c** [comment] 2021-09-17 16:47
The script which made this change was simply copying the (invalid) signature from a duplicate bug as a plain string, it doesn't check if it is valid.

I'm tempted to WONTFIX this, given that it should be very rare.

**Comment by amccreight** [comment] 2021-09-17 17:47
Ok. I filed it in bugbug because that's what the description is on the bot that filed the comment.

Ahh, sorry. I forgot about the dupe signature thing. Yeah, I think that's fine to close it. I mean, I do see it occasionally, but it seems reasonable to take it as is.

**Comment by amccreight** [comment] 2021-09-17 17:49
I guess the actual failing-to-remove-() issue is in the intermittent bug filer, whatever GitHub repo that lives in. :) I guess I'll ask Aryx about that.

**Comment by amccreight** [comment] 2021-09-17 17:56
Ok, I filed a bugzilla bug about TreeHerder leaving in the (): https://bugzilla.mozilla.org/show_bug.cgi?id=1731355

Thanks for your help.

**Comment by marco-c** [comment] 2021-09-17 18:35
> Ok. I filed it in bugbug because that's what the description is on the bot that filed the comment.

Yeah, the name of the bot is a bit confusing. In reality bugbug is behind only a subset of the actions.

**Comment by marco-c** [comment] 2021-09-17 18:36
> Ahh, sorry. I forgot about the dupe signature thing. Yeah, I think that's fine to close it. I mean, I do see it occasionally, but it seems reasonable to take it as is.

Maybe one way to make it clear what's happening and to give a workaround to the user could be to add a comment when adding the signature explaining what the bot is doing.

**Comment by amccreight** [comment] 2021-09-17 21:22
Yes, that could be helpful.

**Closed** 2022-05-09 08:47 UTC
