### ISSUE TITLE
Needinfo added without comment

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#1739] opened 2022-11-03 12:38 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1421435#a155571846_575867

**Comment by suhaibmujahid** [comment] 2022-11-03 13:05
The needinfos were set by the `not_landed` tool

**Comment by suhaibmujahid** [comment] 2022-11-03 13:12
# Last email from the `not_landed` tool 
## [autonag][autofix] Open bugs with no activity for 2 weeks and a r+ patch which hasn't landed for the 2022-11-03
<p>The following bugs have are open with no activity for 2 weeks and a <b>r+</b> patch:
  </p>

Bug | Summary | Assignee
-- | -- | --
... | ... | (Away until Sept 26) Jared Wein [:jaws] (please needinfo? me)
[1651425](https://bugzilla.mozilla.org/show_bug.cgi?id=1651425) | List GPUs instead of hardcoding max 2 in gfxInfo | nobody
[1600437](https://bugzilla.mozilla.org/show_bug.cgi?id=1600437) | Consider removing ECDSA_SHA1 signature algorithm | Darkspirit
[1599061](https://bugzilla.mozilla.org/show_bug.cgi?id=1599061) | The browser window is focused when the Picture-in-Picture is closed on macOS | Markus Stange [:mstange]
[1563452](https://bugzilla.mozilla.org/show_bug.cgi?id=1563452) | When serialising with nsIDocumentEncoder::OutputFormatted, attributes, like href, can be broken across lines, which alters their value (broken links etc.) | Ben Campbell
[1549018](https://bugzilla.mozilla.org/show_bug.cgi?id=1549018) | create a transition plan to prepare for the add-on signing root expiring in 2025 | Rob Wu [:robwu]
[1435148](https://bugzilla.mozilla.org/show_bug.cgi?id=1435148) | --enable-address-sanitizer should --disable-jemalloc | Jesse Schwartzentruber (:truber)
[1425341](https://bugzilla.mozilla.org/show_bug.cgi?id=1425341) | Fail xpcshell tests in case of unexpected TypeError, ReferenceError, SyntaxError | nobody
[1421435](https://bugzilla.mozilla.org/show_bug.cgi?id=1421435) | "Refcounted variable 'this' of type cannot be captured by a lambda" is overly strict | Andi [:andi]
[1392125](https://bugzilla.mozilla.org/show_bug.cgi?id=1392125) | Omitted maxResults property not handled correctly in getRecentlyClosed | nobody
[1375585](https://bugzilla.mozilla.org/show_bug.cgi?id=1375585) | Support WebGL in headless mode | nobody
[1359918](https://bugzilla.mozilla.org/show_bug.cgi?id=1359918) | Add -Wl,-z,now Linker Flags | Mike Hommey [:glandium]
[1290590](https://bugzilla.mozilla.org/show_bug.cgi?id=1290590) | ... | nobody
[1212915](https://bugzilla.mozilla.org/show_bug.cgi?id=1212915) | client hello with malformed session id is accepted | Leander Schwarz
[1199665](https://bugzilla.mozilla.org/show_bug.cgi?id=1199665) | Consider making <input type=number> always fall back to  parsing numbers as English formatted numbers if parsing them as numbers  formatted using the user's locale fails | Jonathan Watt [:jwatt]
[1017237](https://bugzilla.mozilla.org/show_bug.cgi?id=1017237) | Ensure that Sqlite's AsyncShutdown phase displays the name of opened databases in case of crash | nobody
[840706](https://bugzilla.mozilla.org/show_bug.cgi?id=840706)| Make nsTString_CharT::ToDouble/ToFloat output an error code if the string doesn't parse to a finite number | Jonathan Watt [:jwatt]
[651482](https://bugzilla.mozilla.org/show_bug.cgi?id=651482)| Yellow layered Bitmaps | nobody
[571099](https://bugzilla.mozilla.org/show_bug.cgi?id=571099)| Firefox modifies the "color" property for <a> elements in SVG | Robert Longson [:longsonr]
[308565](https://bugzilla.mozilla.org/show_bug.cgi?id=308565)| `altKey` of `keypress` event is always false on macOS | Masayuki Nakano [:masayuki] (he/him)(JST, +0900)

**Comment by suhaibmujahid** [comment] 2022-11-03 13:14
Duplicate of #1527

**Closed by suhaibmujahid** 2022-11-03 13:14 UTC
Labels: bug, area-Noise Reduction
