### ISSUE TITLE
Should we ignore non-defect bugs in autonag triage email?

### ISSUE THREAD

**Issue by hsinyi** [mozilla/relman-auto-nag#853] opened 2019-11-28 12:23 UTC
Since the [are-we-triage-yet dashboard](https://are-we-triaged-yet.herokuapp.com/) presents the reports of defects only according to the [email](https://groups.google.com/d/msg/mozilla.dev.platform/cxlZxbCKKgQ/ih-1leSxAgAJ), I'm thinking if we should consider alignment and ignore non-defect bugs in autonag triage email. Or could we consider make the non-defect bugs P3? Does that sound reasonable? Please let me know if I miss anything.

**Comment by calixteman** [comment] 2019-12-02 09:30
@emceeaich wdyt ?

**Comment by emceeaich** [comment] 2020-02-12 00:47
I don't know if we should auto-triage tasks, the team does need to make a decision about them.

We should not auto-triage enhancements because the product managers on the teams need to make decisions about those, following https://firefox-bug-handling.mozilla.org/new-feature-triage

**Comment by marco-c** [comment] 2021-12-24 14:31
Duplicate of #852.

**Closed by marco-c** 2021-12-24 14:31 UTC
