### ISSUE TITLE
set release status flags when "regressed by" is set

### ISSUE THREAD

**Issue by jcristau** [mozilla/relman-auto-nag#882] opened 2020-02-03 17:29 UTC
For new regressions, it'd save some work to have the bot set status flags to affected/unaffected according to when the bug listed in "regressed by" landed.

**Comment by marco-c** [comment] 2020-04-28 10:45
#238 is a duplicate of this, right?

**Comment by jcristau** [comment] 2020-04-28 11:17
Huh, yes, somehow I missed the earlier one.

**Closed** 2020-04-30 12:10 UTC
Labels: enhancement
