### ISSUE TITLE
Bugbug's bugzilla comments seem to be confusing bug-reporters; maybe they could be clarified a bit?

### ISSUE THREAD

**Issue by dholbert** [mozilla/relman-auto-nag#1059] opened 2021-02-01 21:54 UTC
Right now, Bugbug seems to always post the same text: "Bugbug thinks this bug should belong to this component, but please revert this change in case of error."

I've seen two bugs in the past couple of days where a bug-reporter expressed confusion in reply to this Bugbug comment:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1689789#c3 (where the reporter replied "???")
* https://bugzilla.mozilla.org/show_bug.cgi?id=1690004#c2 (where the reporter replied "what component", presumably not seeing or not-knowing-to-look-for the metadata change)

Perhaps this Bugbug response should be clarified slightly?  It's often the first response of any sort that a new bug reporter will receive when filing their first bug, so it's probably important that it make sense to someone who's new to bugzilla (and isn't familiar with components/etc).

At a minimum, I'd suggest that we make it clearer about what it's doing & what its suggested component is, "Bugbug thinks this bug should belong to the component $NAME-OF-COMPONENT, and is moving the bug to that component, but please revert this change in case of error."

A bit more verbose but probably better: it might be nice to add some friendly salutation, e.g. "Hi! I'm Bugbug, a bugzilla bot that attempts to classify incoming bugs. I think this bug should belong to the component $NAME-OF-COMPONENT, and I'm moving the bug to that component, but please revert this change in case of error."

**Comment by marco-c** [comment] 2021-02-02 09:19
Thanks @dholbert, I've noticed the same lately as a few users started filing Firefox bugs as bugbug repo issues.

Duplicate of #1043.

**Closed by marco-c** 2021-02-02 09:19 UTC
Labels: duplicate
