### ISSUE TITLE
Automatically find performance-related bugs, and request `Performance: ?` on them for triage

### ISSUE THREAD

**Issue by julienw** [mozilla/relman-auto-nag#1390] opened 2022-04-06 16:16 UTC
The Performance flag is something that was added recently to Bugzilla, and can have a few values: P1, P2, P3, ?, - and ---. `?` is used so that this bug goes into the performance triage queue, as described [on the mozilla wiki](https://wiki.mozilla.org/Performance/Triage).

I know you're using some AI magic to automatically move bugs into components, would there be a way to automatically request `Performance: ?` on the bugs that look like performance-related bugs?

Thanks

**Comment by marco-c** [comment] 2022-04-06 18:54
Duplicate of #223.

**Closed by marco-c** 2022-04-06 18:54 UTC
Labels: duplicate
