### ISSUE TITLE
Don't move bugs into components they were just moved out of

### ISSUE THREAD

**Issue by gcp** [mozilla/relman-auto-nag#1082] opened 2021-03-11 10:17 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1695772#c3

Bug was filed in Core::IPC, manually moved out of it, but then the bot moved it back.

**Comment by jcristau** [comment] 2021-03-11 10:19
Duplicate of #877

**Comment by marco-c** [comment] 2021-03-11 10:26
@jcristau this is a new bug, a regression from 4835f12a23e02fe66afb3bf430c23f54c10971b3.

**Comment by gcp** [comment] 2021-03-30 15:17
More cases of this problem:
https://bugzilla.mozilla.org/show_bug.cgi?id=1696337#c4

**Closed** 2021-04-29 13:49 UTC
