### ISSUE TITLE
When "regressed by" is used, update automatically the status flags

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#238] opened 2018-11-07 08:47 UTC
Let say that we have bug XXXXXX which is _regressed by_ bug YYYYYY
As we know in which version bug XXXXX landed, the status flag for bug YYYYYY could be automatically updated.

Idea from Pascal

**Comment by marco-c** [comment] 2020-04-28 11:45
Closing as duplicate of #882.

**Closed by marco-c** 2020-04-28 11:45 UTC
Labels: duplicate, enhancement
