### ISSUE TITLE
No activity for 2 weeks with r+ should not be triggered when there is a backout

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#628] opened 2019-05-02 13:01 UTC
See https://bugzilla.mozilla.org/show_bug.cgi?id=1537669

**Comment by calixteman** [comment] 2019-05-02 13:12
We can do that, but I think, that in such a case the patch should be marked as 'changes-planned' in Phabricator (we handle such a case).

**Comment by marco-c** [comment] 2020-05-12 12:43
Duplicate of #810. This is older but the discussion in #810 is longer

**Closed by marco-c** 2020-05-12 12:43 UTC
Labels: duplicate
